version: 2
jobs:
  build-jar:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # Build it
      - run: gradle build -x test

      - persist_to_workspace:
          root: build/libs
          paths:
            - "*.jar"

  build-image:
    environment:
      IMAGE_NAME: haugene/msga
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: build/libs
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME .
      - run:
          name: Login to Docker Hub
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Push image
          command: docker push $IMAGE_NAME

workflows:
  version: 2
  build-and-package:
    jobs:
      - build-jar
      - build-image:
          context: dockerhub
          requires:
            - build-jar